src/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls",namespace="users")),
    path('', include("web.urls",namespace="web")),
    path('posts/', include("posts.urls",namespace="posts")),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

src/blog/posts/urls.py
from django.urls import path
from posts import views


app_name = "posts"

urlpatterns = [
    path("create/", views.create_post, name="create_post"),
    path("my-posts/", views.my_posts, name="my_posts"),
    path("delete/<int:id>/",views.delete_post, name="delete_post"),
    path("draft/<int:id>/",views.draft_post, name="draft_post"),
    path("edit/<int:id>/",views.edit_post, name="edit_post"),
]

src/blog/web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>/", views.post, name="post"),
]

src/blog/posts/models.py
from distutils.command.upload import upload
from tabnanny import verbose
from turtle import title
from django.db import models
from ckeditor.fields import RichTextField


class Author(models.Model):
    name = models.CharField(max_length=255)
    user = models.OneToOneField("auth.User",on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(models.Model):
    title = models.CharField(max_length=25)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title


class Posts(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    description = RichTextField()
    categories = models.ManyToManyField("posts.Category")
    time_to_read = models.CharField(max_length=128)
    featured_image = models.ImageField(upload_to="posts/")
    is_draft = models.BooleanField(default=False)

    author = models.ForeignKey("posts.Author",on_delete=models.CASCADE)
    published_date = models.DateField()
    
    is_deleted = models.BooleanField(default=False)
 
    def __str__(self):
        return self.title

src/blog/posts/forms.py
from django import forms
from posts.models import Posts


class PostForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={"class":"input"}), label="Tags (Comma seperated)")

    class Meta:
        model = Posts
        exclude = ("author","published_date","is_deleted","categories")

        widgets = {
            "time_to_read" : forms.TextInput(attrs={"class":"input"}),
            "title" : forms.TextInput(attrs={"class":"input"}),
            "short_description" : forms.Textarea(attrs={"class":"input"}),
        }

        error_messages = {
            "time_to_read" : {
                "required" : "Time to read field is required"
            },
            "title" : {
                "required" : "title field is required"
            },
            "description" : {
                "required" : "description field is required"
            },
            "short_description" : {
                "required" : "short description field is required"
            },
            "featured_image" : {
                "required" : "featured image field is required"
            },
            "is_draft" : {
                "required" : "is draft field is required"
            },    
        }

src/blog/posts/views.py
import datetime
import json
from urllib import response
from django.http import HttpResponse

from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required

from posts.forms import PostForm
from posts.models import Author, Category, Posts
from main.functions import generate_form_errors, paginate_instances
from main.decorators import allow_self
 


@login_required(login_url="/users/login/")
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():

            tags = form.cleaned_data["tags"]

            if not Author.objects.filter(user=request.user).exists():
                author = Author.objects.create(user=request.user,name=request.user.username)
            else:
                author = request.user.author

            instance = form.save(commit=False)
            instance.published_date = datetime.date.today()
            instance.author = author
            instance.save()

            tags_list = tags.split(",")
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.categories.add(category)

            response_data = {
                "title": "Succesfully submitted",
                "message" : "Succesfully submitted",
                "status" : "success",
                "redirect" : "yes",
                "redirect_url" : "/",
            }

           
        else:
            error_message= generate_form_errors(form)
            response_data = {
                "title" : "form validation error",
                "message" : str(error_message),
                "status" : "eeror",
                "stable" : "yes",
            }
        return HttpResponse(json.dumps(response_data),content_type="application/json")

    else:
        data = {
            "title": "hello",
            "description": "hello",
            "short_description": "hello",
            "time_to_read": "8 min",
            "tags": "technology,programming,coding",
            
        }
        form = PostForm(initial=data)
        context = {
            "title" : "create new post",
            "form" : form
        }
        return render(request, "posts/create.html", context=context)


@login_required(login_url="/users/login/")
def my_posts(request):
    posts = Posts.objects.filter(author__user=request.user, is_deleted=False)
    instances = paginate_instances(request,posts,per_page=3)
    context = {
        "title" : "My Posts",
        "instances" : instances
    }
    return render(request, "posts/my-posts.html", context=context)



@login_required(login_url="/users/login/")
@allow_self
def delete_post(request,id):
    instance = get_object_or_404(Posts,id=id)
    instance.is_deleted = True
    instance.save()

    response_data = {
        "title" : "Successfully Deleted",
        "message" : "Post deleted successfully",
        "status" : "success",
    }

    return HttpResponse(json.dumps(response_data),content_type="application/json")


@login_required(login_url="/users/login/")
@allow_self
def draft_post(request,id):
    instance = get_object_or_404(Posts,id=id)
    instance.is_draft = not instance.is_draft
    instance.save()

    response_data = {
        "title" : "Successfully changed",
        "message" : "Post updated successfully",
        "status" : "success",
    }

    return HttpResponse(json.dumps(response_data),content_type="application/json")


@login_required(login_url="/users/login/")
@allow_self
def edit_post(request,id):
    Posts.objects.filter(id=id,author__user=request.user)
    instance = get_object_or_404(Posts, id=id)
    if request.method == "POST":
        form = PostForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():

            tags = form.cleaned_data["tags"]

            instance = form.save(commit=False)
            instance.save()

            instance.categories.clear()

            tags_list = tags.split(",")
            for tag in tags_list:
                category, created = Category.objects.get_or_create(title=tag.strip())
                instance.categories.add(category)

            response_data = {
                "title": "Succesfully submitted",
                "message" : "Succesfully submitted",
                "status" : "success",
                "redirect" : "yes",
                "redirect_url" : "/",
            }

           
        else:
            error_message= generate_form_errors(form)
            response_data = {
                "title" : "form validation error",
                "message" : str(error_message),
                "status" : "eeror",
                "stable" : "yes",
            }
        return HttpResponse(json.dumps(response_data),content_type="application/json")

    else:
        category_string =""
        for category in instance.categories.all():
            category_string += f"{category.title},"

        form = PostForm(instance=instance, initial={"tags":category_string[:-1]})
        context = {
            "title" : "create new post",
            "form" : form
        }
        return render(request, "posts/create.html", context=context)

src/blog/templates/posts/create.html
{% extends "base.html" %} {% block content %} {% load static %}
<section id="edit-post-home">
  <section class="wrapper">
    {% include 'web/includes/header.html' %}
    <section class="spotlight">
      <h3>Create new post</h3>
      <form
        action=""
        method="post"
        enctype="multipart/form-data"
        class="ajax redirect"
        enctype="multipart/form-data"
      >
        {% csrf_token %}
        <div class="form-field">
          <label for="{{form.title.id_for_label}}" class="subheads">
            {{form.title.label}}
          </label>
          {{form.title}}
          <div class="form-field">
            <label class="subheads" for="{{form.description.id_for_label}}">
              {{form.description.label}}
            </label>
            <div class="description">{{form.description}}</div>
          </div>
          <div class="form-field">
            <label
              class="subheads"
              for="{{form.short_description.id_for_label}}"
            >
              {{form.short_description.label}}
            </label>
            {{form.short_description}}
          </div>
          <div class="form-field">
            <label class="subheads" for="{{form.tags.id_for_label}}">
              {{form.tags.label}}
            </label>
            {{form.tags}}
          </div>
          <div class="form-field">
            <label for="{{form.time_to_read.id_for_label}}" class="subheads">
              {{form.time_to_read.label}}
            </label>
            {{form.time_to_read}}
          </div>
          <div class="form-field">
            <label for="{{form.featured_image.id_for_label}}" class="subheads">
              {{form.featured_image.label}}
            </label>
            {{form.featured_image}}
          </div>
          <div class="form-field"></div>
          <label class="checkbox">
            {{form.is_draft}} {{form.is_draft.label}}
          </label>
        </div>
        <div class="form-field">
          <input type="submit" value="Submit" />
        </div>
      </form>
      {{form.media}}
    </section>
  </section>
</section>
<!-- <script src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
        <script src="./js/ckeditor.js"></script> -->
<!-- <script>ClassicEditor
            .create( document.querySelector( '.editor' ), {
                
                licenseKey: '',
                
                
                
            } )
            .then( editor => {
                window.editor = editor;
        
                
                
                
            } )
            .catch( error => {
                console.error( 'Oops, something went wrong!' );
                console.error( 'Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:' );
                console.warn( 'Build id: fbn1rnj89y5k-nohdljl880ze' );
                console.error( error );
            } );
        </script> -->
{% endblock %}

src/blog/templates/posts/my-posts.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load paginator_tags %}
        <section id="my-posts-home">
            <section class="wrapper">                
                {% include 'web/includes/header.html' %}
                <section class="spotlight">
                    <h3>
                        {{title}}
                    </h3>
                    <ul class="posts">
                        {% for instance in instances %}
                        <li class="post">
                            <div class="top">
                                <h5 class="title">
                                    {{instance.title}}
                                </h5>
                                <div class="buttons">
                                    <a 
                                    href="{% url 'posts:delete_post' id=instance.id %}" 
                                    class="danger action-button reload"
                                    data-text="Are you sure want to remove this post. You can't undo this action." 
                                    data-title="Confirm Delete!"
                                    title="Delete!"
                                >
                                        <img src="{% static './images/icons/delete.svg' %}" alt="Delete" />
                                    </a>
                                    <a href="{% url 'posts:edit_post' id=instance.id %}" class="warning">
                                        <img src="{% static './images/icons/pencil.svg' %}" alt="Edit" />
                                    </a>
                                    <a 
                                        href="{% url 'posts:draft_post' id=instance.id %}" 
                                        class="{% if instance.is_draft %}success{% else %}danger{% endif %} action-button reload"
                                        data-text="Are you sure want to update this post" 
                                        data-title="Confirm Status!"
                                        title="Draft"
                                    >
                                        <img src="{% static './images/icons/sheet.svg' %}" alt="Edit" />
                                    </a>
                                </div>
                            </div>
                            <p class="description">
                                {{instance.short_description}}
                            </p>
                            <div class="bottom">
                                <a href="{% url 'web:post' id=instance.id %}" class="view">
                                    View
                                    <span>
                                        <img src="{% static './images/icons/up-arrow.svg' %}" alt="Arrow">
                                    </span>
                                </a>
                                <p class="date">
                                    {{instance.published_date}}
                                </p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </section>
                {% load_pagination instances %}
            </section>
        </section>
{% endblock %}